version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Pre-build phase"

  build:
    commands:
      - echo "Build phase"
      - grep -Fq "Congratulations" index.html

  post_build:
    commands:
      - echo "Post-build phase"

